### ISSUE TITLE
Website Bypass

### ISSUE THREAD

**Issue by Blackdarked** [FastForwardTeam/FastForward#975] opened 2023-04-27 09:53 UTC
### Domain

link1s.com

### Link

https://link1s.com/994m

### Version

0.2251

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/46282511/234827440-1a229bdf-9160-4d33-9094-002952d477ca.png)

**Comment by NotAProton** [comment] 2023-04-28 16:42
Duplicate of #40

**Closed as not planned by NotAProton** 2023-04-28 16:42 UTC
Labels: Broken-bypass
