### ISSUE TITLE
Linkvertise not being bypassed

### ISSUE THREAD

**Issue by Dictator6938** [FastForwardTeam/FastForward#985] opened 2023-05-06 13:14 UTC
### Domain

linkvertise.com

### Link

https://linkvertise.com/

### Version

idk

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

When downloading mods specifically Minecraft, fast forward should be able to bypass linkvertise

**Comment by NotAProton** [comment] 2023-05-06 14:57
Duplicate of #963

**Closed as not planned by NotAProton** 2023-05-06 14:57 UTC
Labels: Broken-bypass
