### ISSUE TITLE
Config page pops up every time Edge updates

### ISSUE THREAD

**Issue by AkazaRenn** [FastForwardTeam/FastForward#1099] opened 2023-09-05 02:17 UTC
### Body

This page: extension://ldcclmkclhomnpcnccgbgleikchbnecl/html/options.html, version 0.2279, installed from Edge Extension store: https://microsoftedge.microsoft.com/addons/detail/fastforward/ldcclmkclhomnpcnccgbgleikchbnecl

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by NotAProton** [comment] 2023-09-05 17:39
Duplicate of #1088

**Closed as not planned by NotAProton** 2023-09-05 17:39 UTC
