### ISSUE TITLE
bypass did'nt work on  

### ISSUE THREAD

**Issue by Adityasahu238** [FastForwardTeam/FastForward#938] opened 2023-04-04 09:16 UTC
### Domain

.com

### Link

https://fc-lc.com/

### Version

Latest Version

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

Can't bypass

**Comment by lem6ns** [comment] 2023-04-04 10:52
dupe of #861

**Closed as not planned** 2023-04-04 10:52 UTC
Labels: duplicate
