### ISSUE TITLE
Za.gl isn't bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#250] opened 2021-12-08 14:06 UTC
### Domain

Za.gl

### Link

https://za.gl/Zn61My

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2021-12-08 16:24
Duplicate of #53 

Fixed in https://github.com/FastForwardTeam/FastForward/commit/10a19e1b9d6031e807135b05f9e3bf79fd57eff2

**Closed as completed by NotAProton** 2021-12-08 16:24 UTC
Labels: New-bypass
