### ISSUE TITLE
Firefox 112 Error: Add-on not verfied

### ISSUE THREAD

**Issue by 99thim** [FastForwardTeam/FastForward#958] opened 2023-04-17 08:04 UTC
### Body

I am unable to instal the addon version 0.2251 on Firefox manually and I am getting an error message that the addon hasnt been verified even I setup xpinstall.signatures.required to FALSE, closed and restarted Firefox (several times). I have checked that when I restarting Forefox  that xpinstall.signatures.required is correctly setup tp FALSE. I am using Firefox 112 on a Mac. I had the previous version 0.2039 before. Not sure what I am missing here...

### Version

0.2251

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

MacOS

### Anything else?

n/a

**Comment by NotAProton** [comment] 2023-04-17 09:46
Duplicate of #947 
See https://github.com/FastForwardTeam/FastForward/releases/tag/0.2237

**Closed as not planned by NotAProton** 2023-04-17 09:46 UTC

**Comment by 99thim** [comment] 2023-04-18 00:11
OK. You should make it clear in your wiki to users they can't expect to install the addon on a mainstream FF channel since this won't be resolvable without one using FF Nighlty.

**Comment by NotAProton** [comment] 2023-04-18 01:25
You can install the signed version from the release I linked https://github.com/FastForwardTeam/FastForward/releases/download/0.2237/fastforwardteam-0.2237.xpi

**Comment by 99thim** [comment] 2023-04-18 03:53
Many thsnka
