### ISSUE TITLE
Bitly Lofi-girl shop bypass

### ISSUE THREAD

**Issue by r-garciag** [FastForwardTeam/FastForward#1314] opened 2024-01-09 11:54 UTC
### Link

https://bit.ly/Iofigirl-shop

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by NotAProton** [comment] 2024-02-01 07:01
Duplicate of #1297

**Closed as not planned by NotAProton** 2024-02-01 07:01 UTC
Labels: Broken-bypass
