### ISSUE TITLE
[Bug] Extension page opens up instead of bit.ly

### ISSUE THREAD

**Issue by AppleMangoOrange** [FastForwardTeam/FastForward#1192] opened 2023-10-18 07:29 UTC
### Body

Opening the link http://bit.ly/WatchBrooklyn99Peacock Redirects to the extension page that says 
"You aren't supposed to be here
Please open an issue on github to report this error.."

Extension version is 0.2334-Mv3 on Firefox, POP OS.

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by NotAProton** [comment] 2023-10-18 11:11
Enable this permission https://github.com/FastForwardTeam/FastForward/issues/1150#issuecomment-1748963835

Duplicate of #1190

**Closed as not planned by NotAProton** 2023-10-18 11:11 UTC
