### ISSUE TITLE
intercelestial.com

### ISSUE THREAD

**Issue by rahaaatul** [FastForwardTeam/FastForward#370] opened 2022-02-23 05:20 UTC
### Domain

https://intercelestial.com/

### Link

https://intercelestial.com/?id=ZmQ0bjRncFBHSXlINm5Vc3RtTWRQV0kzcG1PSUpaK1RvcTVPN25mUy9Pdys2VUpoYSt4NmJRNEhUdG9Tb0NLcC80dE55Q2ZyQjZXdG1lMG1IcnRQakRGSzVHQ3AzRk1HZTJqZmFFcUU3YmpkMFF1VmdSUE1nUXZKUFJ3QTlYWXN6ZzZ2QXk0dDNvb3JhcE55d2huUmFPdytlbXoxMm5xQm1td1R3T1NndWdIQUZsM3BmRXgzWmNkRnBWdVpSbkhvd3BFVDRjN3dXZE9PNWRLSHI2VXc0QT09

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

_I'm not a robot > (WAIT) > Generate Links > (WAIT) > Download_
Sometimes goes to [Linegee](https://linegee.net/?link=4248cd3f7b&hash=2fe568786fe06f38528a9a93b8466ac6&sign=a57ee72b96be7240be73c6e075886781) domain and have to click continue to access the file
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2022-02-23 10:22
Duplicate of #358

**Closed as completed by NotAProton** 2022-02-23 10:22 UTC
Labels: New-bypass
