### ISSUE TITLE
www.interselestial.com

### ISSUE THREAD

**Issue by ThaRealJozef** [FastForwardTeam/FastForward#395] opened 2022-03-10 22:02 UTC
### Domain

https://intercelestial.com

### Link

https://intercelestial.com/supercomputer/#

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Brave, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

This is the first link : https://intercelestial.com/?id=MlhQdDdyNmE0TkI2bGljbXhVODBWSzMwWWIzc1QwMXIwaUdWYlV4dXpGdWtRTmlsc3BKcmdyZUhFR1B5bzRZbno1OHY2ayt4OWd6cE5ZcFFYYUNCT2hNbVNZaUNmMS92SkxOTVJtMzBlVHU1eU1nbS9SWStzUHo5eER2ekVLMW9yd0hodTcwUHQyR3JGa1hGYXQ4THpvc0lLNXkzOWtWakxacTJGa01oU2RydXZCcWt6TDY4Qkppek9pT1pyWUMwSlRjK3RvRG1ZQS9NNUxjaGdad1lnZz09

It automatically switches to this : https://intercelestial.com/supercomputer/#

Then when clicking generate link (as in the photo provided) it will scroll you down the page to a download button(which is provided also), there is the link when clicking generate the link : https://intercelestial.com/supercomputer/#generate

And after clicking on download as i mentioned before it goes to linegee.com but it's not a problem i think

**I know that this issue is here already but it's not solved until now and all i can say is that's pain in a$$.
Please solve this asap if possible.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2022-03-13 13:40
Duplicate of #25

**Closed as completed by NotAProton** 2022-03-13 13:40 UTC
Labels: New-bypass
