### ISSUE TITLE
Gestyy isn´t by pass

### ISSUE THREAD

**Issue by Juniorjoose** [FastForwardTeam/FastForward#259] opened 2021-12-14 16:00 UTC
### Domain

http://gestyy.com/

### Link

http://gestyy.com/ep965w NSFW

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Juniorjoose** [comment] 2021-12-14 16:04
shorte.st banner appear

**Comment by NotAProton** [comment] 2021-12-14 16:24
Duplicate of #47

**Closed as completed by NotAProton** 2021-12-14 16:24 UTC
Labels: New-bypass
