### ISSUE TITLE
exe.io isn't passed

### ISSUE THREAD

**Issue by danteyc** [FastForwardTeam/FastForward#287] opened 2021-12-28 14:18 UTC
### Domain

https://exe.io

### Link

http://exe.io/yVH9YH

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2021-12-29 05:34
Duplicate of #117

**Closed as completed by NotAProton** 2021-12-29 05:34 UTC
Labels: New-bypass
