### ISSUE TITLE
Loan2Host

### ISSUE THREAD

**Issue by Amakuza77** [FastForwardTeam/FastForward#1246] opened 2023-11-21 04:08 UTC
### Link

https://tii.la/IuKPx

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by NotAProton** [comment] 2023-11-27 22:58
Duplicate of #1170

**Closed as not planned by NotAProton** 2023-11-27 22:58 UTC
Labels: New-bypass
