### ISSUE TITLE
Timer is not bypassed

### ISSUE THREAD

**Issue by Roitsquad** [FastForwardTeam/FastForward#159] opened 2021-10-08 12:14 UTC
### Domain

https://link1s.com

### Link

https://link1s.com/8fmlkxola

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2021-10-08 16:37
Duplicate of #40

**Closed as completed by NotAProton** 2021-10-08 16:37 UTC
Labels: New-bypass
