### ISSUE TITLE
FastForward is not working with https://gplinks.co/

### ISSUE THREAD

**Issue by rynaazsha** [FastForwardTeam/FastForward#334] opened 2022-02-01 17:44 UTC
### Domain

https://gplinks.co/

### Link

https://gplinks.co/L7r0

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

Tested with below links, multiple tests but no lucks... Dev team, need your kind support

[https://gplinks.co/L7r0](url)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2022-02-02 08:00
Duplicate of #128

**Closed as completed by NotAProton** 2022-02-02 08:00 UTC
Labels: New-bypass
