### ISSUE TITLE
link1s.com

### ISSUE THREAD

**Issue by blazesprings** [FastForwardTeam/FastForward#394] opened 2022-03-10 09:22 UTC
### Domain

https://link1s.com/

### Link

https://link1s.com/yDD4f7

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://link1s.com/yDD4f7
There  are 4 timers each of 10 sec. Please hellp bypass the website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2022-03-13 13:38
Duplicate of #40

**Closed as completed by NotAProton** 2022-03-13 13:38 UTC
Labels: New-bypass
