### ISSUE TITLE
NBAbite no longer bypassing but redirecting to default page

### ISSUE THREAD

**Issue by nightzeyy** [FastForwardTeam/FastForward#428] opened 2022-04-10 01:47 UTC
### Domain

https://scor.nbabite.com/

### Link

https://scor.nbabite.com/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

When using nbabite it normally redirects to the links provided now it redirects to the default page https://nbastreams.app/

**Comment by Write** [comment] 2022-04-10 19:37
Duplicate of https://github.com/FastForwardTeam/FastForward/issues/430

**Closed as completed** 2022-04-13 07:29 UTC
Labels: Broken-bypass
