### ISSUE TITLE
Broken Bypass on Ouo

### ISSUE THREAD

**Issue by ghost** [FastForwardTeam/FastForward#966] opened 2023-04-21 21:34 UTC
### Domain

https://ouo.io/

### Link

https://ouo.io/9ZrsEG

### Version

0.2251

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

It was working a week ago, but it no longer works.

**Comment by NotAProton** [comment] 2023-04-22 05:01
Duplicate of #861

**Closed as not planned by NotAProton** 2023-04-22 05:01 UTC
Labels: Broken-bypass
