### ISSUE TITLE
go.netfile.cc

### ISSUE THREAD

**Issue by ahmed98Osama** [FastForwardTeam/FastForward#149] opened 2021-10-06 09:27 UTC
### Domain

go.netfile.cc

### Link

https://go.netfile.cc/MxAu

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2021-10-06 10:23
Duplicate of #117 

Fixed in https://github.com/FastForwardTeam/FastForward/commit/a53f1cf03f4fde3c0ee6d9a95ae028d70695fdf6

**Closed as completed** 2021-12-11 06:18 UTC
Labels: CrowdBypass
