### ISSUE TITLE
bypass suggestion - exey.io

### ISSUE THREAD

**Issue by qqzero0** [FastForwardTeam/FastForward#224] opened 2021-11-27 10:33 UTC
### Domain

https://exey.io

### Link

https://exey.io/Nuno3S

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2021-11-27 15:56
Duplicate of #150

**Closed as completed by NotAProton** 2021-11-27 15:56 UTC
Labels: New-bypass
