### ISSUE TITLE
Bypass not working on megaup.net (NSFW)

### ISSUE THREAD

**Issue by Manidarean5** [FastForwardTeam/FastForward#970] opened 2023-04-23 08:45 UTC
### Domain

https://megaup.net

### Link

Example link: https://megaup.net/1TAzt/The_bot.png but when i wait: https://download.megaup.net/?idurl=0lixLaV5L89JKamcHXUbeswkcyY8BAN%2BwO2I0DGIPkOSdArt%2Bnk0DNkgT1vgbt%2BolX%2FcKYgLNoasii3YQX0Oq4zGpDA0iZ%2BnmmQzQaGZYPk%3D&idfilename=The+bot.png&idfilesize=35.00+KB

### Version

Last

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Example link: https://megaup.net/1TAzt/The_bot.png
but when i wait: https://download.megaup.net/?idurl=0lixLaV5L89JKamcHXUbeswkcyY8BAN%2BwO2I0DGIPkOSdArt%2Bnk0DNkgT1vgbt%2BolX%2FcKYgLNoasii3YQX0Oq4zGpDA0iZ%2BnmmQzQaGZYPk%3D&idfilename=The+bot.png&idfilesize=35.00+KB

**Comment by SrIzan10** [comment] 2023-04-26 19:10
according to the [bypass checker](https://fastforward.team/bypass-checker) website, megaup is not supported
its safe to close the issue

**Comment by NotAProton** [comment] 2023-04-30 06:12
Search existing issues before opening new ones
Duplicate of #965

**Closed as completed by NotAProton** 2023-04-30 06:12 UTC
Labels: Broken-bypass
