### ISSUE TITLE
https://linkpoi.me/tWT2KzN3

### ISSUE THREAD

**Issue by dhana-exe** [FastForwardTeam/FastForward#116] opened 2021-09-24 16:52 UTC
### Domain

https://linkpoi.me/

### Link

https://linkpoi.me/tWT2KzN3

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2021-09-25 15:35
Duplicate of #36

Closing

**Closed as completed by NotAProton** 2021-09-25 15:35 UTC
Labels: New-bypass
