### ISSUE TITLE
stfly.me

### ISSUE THREAD

**Issue by josesilveiraa** [FastForwardTeam/FastForward#365] opened 2022-02-17 00:09 UTC
### Domain

https://stfly.me/

### Link

https://stfly.me/6Mrrrii

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2022-02-18 09:58
Duplicate of #143

**Closed as completed by NotAProton** 2022-02-18 09:58 UTC
Labels: New-bypass
