### ISSUE TITLE
Please add a bypass for work.ink

### ISSUE THREAD

**Issue by Little-Night-Wolf** [FastForwardTeam/FastForward#326] opened 2022-01-29 21:06 UTC
### Domain

https://work.ink/

### Link

https://work.ink/en/l/3w/XENOSX64

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

The website is similar to linkvertise and its ads are very annoying and abusive

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2022-02-02 08:02
Duplicate of #299

**Closed as completed by NotAProton** 2022-02-02 08:02 UTC
Labels: New-bypass
