### ISSUE TITLE
Extension gone from firefox web store

### ISSUE THREAD

**Issue by rezadk56** [FastForwardTeam/FastForward#951] opened 2023-04-13 03:10 UTC
### Body

Extension gone from firefox web store. How can i install fastforward on firefox? When i tried to use manual way, with downlaod the rar file and manually load from extension settings in firefox, it said that the extension is not valid or something, so i still can't install it, please fix this issue

### Version

.

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![Screenshot_1](https://user-images.githubusercontent.com/65821032/231638687-0f0d2673-5d5c-49ee-b0e1-a124fc92615a.png)

**Comment by SpaceMageWhatever** [comment] 2023-04-13 10:38
i uploaded the file i had in my folder before the extension got removed from firefox
https://www.mediafire.com/file/t6buj51h07g7bu1/addon%2540fastforward.team.xpi/file

**Comment by NotAProton** [comment] 2023-04-13 14:15
Duplicate of #920

**Closed as not planned by NotAProton** 2023-04-13 14:15 UTC
