### ISSUE TITLE
Broken bit.ly

### ISSUE THREAD

**Issue by DorkYBru** [FastForwardTeam/FastForward#1325] opened 2024-01-14 01:05 UTC
### Link

https://bit.ly/3tKYoSI

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers, Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by NotAProton** [comment] 2024-02-01 06:57
Duplicate of #1297

**Closed as not planned by NotAProton** 2024-02-01 06:57 UTC
Labels: Broken-bypass
