### ISSUE TITLE
bit.ly broken

### ISSUE THREAD

**Issue by privacyguy123** [FastForwardTeam/FastForward#1296] opened 2023-12-23 09:59 UTC
### Link

bit.ly/123

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

Check it

**Comment by Laesx** [comment] 2023-12-29 13:25
I'm seeing this too, seems something broke with the apimon.de implementation or something cause t.co also fails. It should just let you through the regular link in that case and not stuck you in a loop as it does now.

**Comment by NotAProton** [comment] 2023-12-30 14:56
Duplicate of #1297

**Closed as not planned by NotAProton** 2023-12-30 14:56 UTC
Labels: Broken-bypass
