### ISSUE TITLE
Bypass not working on intercelestial.com

### ISSUE THREAD

**Issue by Dolaaz** [FastForwardTeam/FastForward#969] opened 2023-04-23 04:06 UTC
### Domain

intercelestial.com

### Link

intercelestial.com

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

nothing else

**Comment by NotAProton** [comment] 2023-04-29 15:26
Duplicate of #816

**Closed as completed by NotAProton** 2023-04-29 15:26 UTC
Labels: Broken-bypass
