### ISSUE TITLE
Gestyy.com isn't bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#251] opened 2021-12-08 14:09 UTC
### Domain

Gestyy.com

### Link

http://gestyy.com/eqqhf0

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment] 2021-12-08 16:21
Duplicate of #47

**Closed as completed by NotAProton** 2021-12-08 16:21 UTC
Labels: New-bypass
