### ISSUE TITLE
Was browsing posts on Nitter, clicked link from a dub translator bot out of curiosity, got an error screen from FastForward

### ISSUE THREAD

**Issue by adamantris** [FastForwardTeam/FastForward#1301] opened 2024-01-01 18:01 UTC
### Link

http://bit.ly/3WUC0iq

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

Was browsing the weird/funny conspiracy side of Twitter by using Nitter ([link to post specifically](https://nitter.adminforge.de/ZhuDu4857/status/1741524344327614814#m)) out of boredom. Saw a user mentioning a dubbing bot, so got curious and clicked on the shortened Youtube URL (which actually redirects to the [chrome web store](https://chromewebstore.google.com/detail/ezdubs/ecjedckgmjgofdaboinpkeehgiloajhg)), which afterwards FastForward gave me this error:

![Screenshot_20240101_184903](https://github.com/FastForwardTeam/FastForward/assets/152009291/9ca93a92-8060-484a-9ca8-450b3788b1b6)

Some additional info:

OS: Kubuntu 23.10
Browser version: Firefox v118.0.1
Plugin version: 0.2334-Mv3
Screenshot of my extension settings:

![Screenshot_20240101_185508](https://github.com/FastForwardTeam/FastForward/assets/152009291/54b9b430-b7e6-41c0-bcc8-4dda3f693543)
(got no entry in the whitelist)

**Comment by NotAProton** [comment] 2024-01-08 03:41
Duplicate of #1297

**Closed as not planned by NotAProton** 2024-01-08 03:41 UTC
Labels: Broken-bypass
