### ISSUE TITLE
Stfly.me i cant bypass

### ISSUE THREAD

**Issue by Kaltvien** [FastForwardTeam/FastForward#945] opened 2023-04-07 16:48 UTC
### Domain

https://stfly.me/

### Link

https://stfly.me/P4Bh

### Version

0.2243

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Nothing more i cant access

**Comment by lem6ns** [comment] 2023-04-07 17:56
dupe of #799

**Closed as not planned** 2023-04-07 17:56 UTC
Labels: Broken-bypass
